use master
GO
IF DB_ID('QUANLIKHACHSAN') IS NULL
	BEGIN
	CREATE DATABASE QUANLIKHACHSAN;
	USE QUANLIKHACHSAN;
	END;
GO


IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='NHANVIEN')
BEGIN
CREATE TABLE NHANVIEN(
MANV INT IDENTITY(1,1),
TENNV NVARCHAR(50),
SDT VARCHAR(10) unique,
EMAIL VARCHAR(50),
DIACHI NVARCHAR(200),
PRIMARY KEY (MANV)
);
END;
GO




IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='KHACHHANG')
BEGIN
CREATE TABLE KHACHHANG (
   MADOAN INT,
   MAKH INT IDENTITY(1,1),
   CCCD_PASSPORT VARCHAR(12),
   TENKH NVARCHAR(50),
   SDT VARCHAR(10),
   EMAIL VARCHAR(50),
   DIACHI NVARCHAR(200),
   QUOCTICH NVARCHAR(50),
   PRIMARY KEY(MAKH)
);
END;
GO

IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='DOAN')
BEGIN
CREATE TABLE DOAN (
   MADOAN INT IDENTITY(1,1),
   TENDOAN NVARCHAR(50),
   TRUONGDOAN INT,
   SONGUOI INT,
   PRIMARY KEY(MADOAN),
   FOREIGN KEY(TRUONGDOAN) REFERENCES KHACHHANG(MAKH)
);
END;
GO

IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='DOITACDICHVU')
BEGIN
CREATE TABLE DOITACDICHVU (
   MADOITACDV INT IDENTITY(1,1),
   TENDOITAC NVARCHAR(50),
   SDT VARCHAR(10),
   EMAIL VARCHAR(50),
   DIACHI NVARCHAR(200),
   PRIMARY KEY(MADOITACDV)
);
END;
GO


IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='DAILYTRUNGGIAN')
BEGIN
CREATE TABLE DAILYTRUNGGIAN (
   MADAILY INT IDENTITY(1,1),
   TENDAILY NVARCHAR(50),
   SDT VARCHAR(10),
   EMAIL VARCHAR(50),
   DIACHI NVARCHAR(200),
   PRIMARY KEY(MADAILY)
);
END;
GO


IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='LOAIPHONG')
BEGIN

CREATE TABLE LOAIPHONG (
	MALP INT IDENTITY(1,1),
	TENLP NVARCHAR(50),
	HANGPHONG NVARCHAR(50),
	DONGIA DECIMAL,
	MOTA NVARCHAR(200),
	PRIMARY KEY (MALP),
);
END;
GO


IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='PHONG')
BEGIN
CREATE TABLE PHONG (
	MAPHONG INT IDENTITY(1,1) ,
	MALP INT,
	TINHTRANGTHUE NVARCHAR(50) CHECK (TINHTRANGTHUE IN (N'ĐÃ CHO THUÊ', N'CÒN TRỐNG')),
	TINHTRANGVESINH NVARCHAR(50) CHECK (TINHTRANGVESINH IN (N'ĐÃ VỆ SINH ', N'CHƯA VỆ SINH')),
	PRIMARY KEY (MAPHONG),
	FOREIGN KEY (MALP) REFERENCES LOAIPHONG(MALP)
);
END;
GO

ALTER TABLE PHONG 
ADD FOREIGN KEY (MALP) REFERENCES LOAIPHONG(MALP)


IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='COSOVATCHAT')
BEGIN
CREATE TABLE COSOVATCHAT (
	MAVATCHAT INT IDENTITY(1,1) ,
	TENVATCHAT NVARCHAR(100),
	GIA DECIMAL,
	PRIMARY KEY ( MAVATCHAT )
);
END;
GO


IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='PHONG_CSVC')
BEGIN
CREATE TABLE PHONG_CSVC (
	MAPHONG INT,
	MA_CSVC INT,
	SOLUONG INT,
	PRIMARY KEY(MAPHONG, MA_CSVC),
	FOREIGN KEY(MA_CSVC) REFERENCES COSOVATCHAT(MAVATCHAT)
	);
END;
GO


IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='PHIEUDATPHONG')
BEGIN
CREATE TABLE PHIEUDATPHONG (
	MADP INT IDENTITY(1,1),
	MADAILY INT,
	NGUOIDAT INT,
	NGAYDEN DATE,
	NGAYDI DATE,
	YEUCAUDACBIET NVARCHAR(200),
	HINHTHUCDATPHONG NVARCHAR(50) CHECK (HINHTHUCDATPHONG IN(N'TRỰC TIẾP',N'TRUNG GIAN')) ,
	NGAYDAT DATE,
	TIENCOC DECIMAL,
	CHIPHIUOCTINH DECIMAL,
	SONGUOI INT,
	SOPHONG INT,
	GIAHAN NVARCHAR(50) CHECK ( GIAHAN IN(N'CÓ', N'KHÔNG'))
	PRIMARY KEY (MADP)
);
END;
GO
---



IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='PHIEUNHANPHONG')
BEGIN
CREATE TABLE PHIEUNHANPHONG (
   MAPNP INT IDENTITY(1,1),
   KHACHNHANPHONG INT,
   MADATPHONG INT,
   THOIDIEMNHAN DATETIME,
   MAPHONG INT,
   NGUOILAP INT,

   PRIMARY KEY(MAPNP),
   FOREIGN KEY(KHACHNHANPHONG) REFERENCES KHACHHANG(MAKH),
   FOREIGN KEY(MADATPHONG) REFERENCES PHIEUDATPHONG(MADP),
   FOREIGN KEY(MAPHONG) REFERENCES PHONG(MAPHONG),
   FOREIGN KEY(NGUOILAP) REFERENCES NHANVIEN(MANV)
);
END;
GO

IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='DV_TAICHO')
BEGIN
CREATE TABLE DV_TAICHO(
	MADVTC INT IDENTITY(1,1),
	TENDV NVARCHAR(50),
	DONVITINH NVARCHAR(50),
	GIA DECIMAL,
	PRIMARY KEY (MADVTC)
);
END;
GO


IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='DVTC_LP_HOTRO')
BEGIN
CREATE TABLE DVTC_LP_HOTRO (
   MALP INT,
   MADVTC INT,

   PRIMARY KEY(MALP,MADVTC),
   FOREIGN KEY(MALP) REFERENCES LOAIPHONG(MALP),
   FOREIGN KEY(MADVTC) REFERENCES DV_TAICHO(MADVTC)
);
END;
GO


IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='PHIEUDANGKI_DVTC')
BEGIN
CREATE TABLE PHIEUDANGKI_DVTC(
	MADVTC INT,
	MAPNP INT,
	THOIDIEMSUDUNG DATETIME,
	THOIDIEMDANGKY DATETIME,
	PHITAMTHOI DECIMAL,
	PRIMARY KEY (MADVTC,MAPNP),
	FOREIGN KEY(MADVTC) REFERENCES DV_TAICHO(MADVTC),
	FOREIGN KEY(MAPNP)  REFERENCES PHIEUNHANPHONG(MAPNP) 
);
END;
GO


IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='CHINHSACH')
BEGIN
CREATE TABLE CHINHSACH(
	MACS INT IDENTITY(1,1),
	TENCS NVARCHAR(50),
	THOIGIANAPDUNG DATETIME,
	PRIMARY KEY (MACS)
);
END;
GO


IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='APDUNGCHINHSACH')
BEGIN
CREATE TABLE APDUNGCHINHSACH(
	MACS INT ,
	MAPDP INT,
	THOIGIANBATDAU DATETIME,
	THOIGIANKETTHUC DATETIME
	PRIMARY KEY (MACS,MAPDP),
	FOREIGN KEY(MACS) REFERENCES CHINHSACH(MACS),
	FOREIGN KEY(MAPDP)REFERENCES PHIEUDATPHONG(MADP)
);
END;
GO



IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='DOITACDICHVU')
BEGIN
CREATE TABLE DOITACDICHVU (
	MADOITACDV INT IDENTITY(1,1),
	TENDOITAC NVARCHAR(50),
	SDT VARCHAR(10),
	EMAIL VARCHAR(50),
	DIACHI NVARCHAR(200),
    PRIMARY KEY(MADOITACDV)
);
END;
GO




IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='DICHVUHOPTAC')
BEGIN
CREATE TABLE DICHVUHOPTAC(
	MADVHT INT IDENTITY(1,1),
	MADOITACDV INT,
	TENDV NVARCHAR(100),
	GIA DECIMAL,
	PRIMARY KEY (MADVHT),
	FOREIGN KEY (MADOITACDV) REFERENCES DOITACDICHVU(MADOITACDV)
);
END;
GO


IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='PHIEUDANGKI_DVHT')
BEGIN
CREATE TABLE PHIEUDANGKI_DVHT(
	MADP INT,
	MADVHT INT,
	SONGUOI INT,
	THOIGIANKHOIHANH DATETIME,
	DICHUYEN NVARCHAR(20) CHECK (DICHUYEN IN(N'ĐƯA ĐÓN',N'TỰ TÚC')),
	TINHTRANGDUYET NVARCHAR(20) CHECK (TINHTRANGDUYET IN(N'CHƯA DUYỆT',N'ĐỒNG Ý',N'ĐÃ DUYỆT',N'TỪ CHỐI')),
	--LÀ NHÂN VIÊN KHÁCH SẠN CHƯA GỞI THÔNG TIN QUA CHO ĐỐI TÁC DU LỊCH,
	--CÒN ĐỒNG Ý LÀ BÊN ĐỐI TÁC DU LỊCH XÁC NHẬN ĐƠN, 'TỪ CHỐI' LÀ ĐỐI TÁC KHÔNG NHẬN
	--ĐÃ DUYỆT LÀ NHÂN VIÊN KHÁCH SẠN ĐÃ GỞI THÔNG TIN QUA CHO ĐỐI TÁC DU LỊCH
	THOIGIANKETTHUC DATETIME

	 PRIMARY KEY (MADVHT,MADP),
	 FOREIGN KEY(MADVHT) REFERENCES DICHVUHOPTAC(MADVHT),
	 FOREIGN KEY(MADP)  REFERENCES PHIEUDATPHONG(MADP)
);
END;
GO



IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='HONGHOC')
BEGIN
CREATE TABLE HONGHOC (
	MAHONGHOC INT IDENTITY(1,1),
	MAPNP INT,
	MAVATCHAT INT,
	SOLUONG INT,
	PRIMARY KEY (MAHONGHOC),
	FOREIGN KEY (MAPNP) REFERENCES PHIEUNHANPHONG(MAPNP), 
	FOREIGN KEY (MAVATCHAT) REFERENCES COSOVATCHAT(MAVATCHAT)
);
END;
GO


IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='GIAHAN')
BEGIN
CREATE TABLE GIAHAN(
	STT INT IDENTITY(1,1),
	MADP INT,
	THOIGIANGIAHAN INT,
	TINHTRANGDUYET NVARCHAR(50) CHECK ( TINHTRANGDUYET IN (N'CHƯA DUYỆT',N'ĐÃ DUYỆT', N'TỪ CHỐI')),
	PRIMARY KEY (STT,MADP),
	FOREIGN KEY (MADP) REFERENCES PHIEUDATPHONG(MADP)
	);
END;
GO

IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='PHIEUTRAPHONG')
BEGIN

CREATE TABLE PHIEUTRAPHONG(
	MATP INT IDENTITY(1,1),
	NGAYCHECKOUT DATETIME,
	MADP INT,
	PRIMARY KEY(MATP),
	FOREIGN KEY (MADP) REFERENCES PHIEUDATPHONG(MADP)
);
END;
GO



IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='PHIEUPHANHOI')
BEGIN
CREATE TABLE PHIEUPHANHOI(
	MAPH INT IDENTITY(1,1),
	NOIDUNG NVARCHAR(200),
	MATP INT,
	DANHGIA NVARCHAR(50) CHECK ( DANHGIA IN (N'RẤT HÀI LÒNG',N'HÀI LÒNG', N'KHÔNG HÀI LÒNG')),
	PRIMARY KEY(MAPH),
	FOREIGN KEY (MATP) REFERENCES PHIEUTRAPHONG(MATP)

);
END;
GO



IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='HOADON')
BEGIN
CREATE TABLE HOADON(
	MAHOADON INT IDENTITY(1,1),
	MATP INT,
	THOIDIEMTHANHTOAN DATETIME,
	HINHTHUCTHANHTOAN NVARCHAR(50) CHECK ( HINHTHUCTHANHTOAN IN (N'TIỀN MẶT', N'CHUYỂN KHOẢN')),
	TIENCOC DECIMAL,
	TONGTIEN DECIMAL,
	NGUOILAPHOADON INT,
	PRIMARY KEY (MAHOADON),
	FOREIGN KEY (MATP) REFERENCES PHIEUTRAPHONG(MATP),
	FOREIGN KEY (NGUOILAPHOADON) REFERENCES NHANVIEN(MANV)
);
END;
GO



IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='CHITIETHOADON')
BEGIN
CREATE TABLE CHITIETHOADON(
	MAHOADON INT,
	STT INT IDENTITY (1,1),
	DV_CSVC NVARCHAR(50),
	SOLUONG INT,
	THANHTIEN DECIMAL,
	PRIMARY KEY(MAHOADON,STT),
	FOREIGN KEY (MAHOADON) REFERENCES  HOADON(MAHOADON)

--??? dv_csdv nó không liên kết đc ???


);
END;
GO



IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='KS_DOITAC')
BEGIN

CREATE TABLE KS_DOITAC(
	MAKSDT INT IDENTITY(1,1),
	TENKS NVARCHAR(50),
	MOTA NVARCHAR(200),
	DIACHI NVARCHAR(200),
	EMAIL VARCHAR(50),
	SDT VARCHAR(10),
);
END;
GO

IF NOT EXISTS (SELECT *
FROM information_schema.tables
WHERE TABLE_NAME='TAIKHOAN')
BEGIN
CREATE TABLE TAIKHOAN(
	USERNAME NVARCHAR(50) ,
	U_PASSWORD NVARCHAR(50),
	MANV INT,
	VAITRO NVARCHAR(50) CHECK (VAITRO IN( N'LỄ TÂN',N'BELLMAN',N'BUỒNG PHÒNG'))
	PRIMARY KEY ( MANV),
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
END
